# Generated by Django 3.1 on 2020-09-08 13:52

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_project_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_description',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
