# Generated by Django 3.1 on 2020-09-09 17:25

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20200909_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='tracker_description',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
