# Generated by Django 3.1 on 2020-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20200911_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='database_used',
            field=models.ManyToManyField(blank=True, to='base.Database'),
        ),
        migrations.AlterField(
            model_name='project',
            name='framework_used',
            field=models.ManyToManyField(blank=True, to='base.Framework'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language_used',
            field=models.ManyToManyField(blank=True, to='base.Language'),
        ),
    ]
