# Generated by Django 3.1 on 2020-09-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_remove_aboutme_igname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='igname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
