# Generated by Django 3.1 on 2020-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(null=True),
        ),
    ]
