# Generated by Django 3.1 on 2020-09-02 15:25

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('tracking_id', hashid_field.field.HashidAutoField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', min_length=8, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(default='New Feature', max_length=50)),
                ('feature_description', models.TextField(default='Feature Description', max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Working', 'Workng'), ('Discarded', 'Discarded'), ('Completed', 'Completed')], default='Queued', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', hashid_field.field.HashidAutoField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', min_length=8, primary_key=True, serialize=False)),
                ('project_title', models.CharField(default='New Project', max_length=200)),
                ('project_description', models.TextField(default='Project Description', max_length=2000)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Working', 'Workng'), ('Completed', 'Completed')], default='Working', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('trackerid', hashid_field.field.HashidAutoField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', min_length=8, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tracker_title', models.CharField(default='Progress', max_length=50)),
                ('tracker_description', models.TextField(default='Description', max_length=200)),
                ('tracking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.feature')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project'),
        ),
    ]
