# Generated by Django 3.1 on 2020-09-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200902_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
