# Generated by Django 3.1 on 2020-09-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200904_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='choice1',
            field=models.CharField(choices=[('Extremely useful', 'Extremely useful'), ('Somewhat useful', 'Somewhat useful'), ('Not useful', 'Not useful')], editable='false', max_length=100),
        ),
    ]
