# Generated by Django 3.1 on 2020-09-05 11:23

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20200905_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
