# Generated by Django 3.1 on 2020-09-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20200908_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project'),
        ),
    ]
