# Generated by Django 3.1 on 2020-09-09 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_progress_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='trackerid',
            new_name='tracker_id',
        ),
        migrations.AddField(
            model_name='progress',
            name='progress_precentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
