# Generated by Django 3.1 on 2020-09-10 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_progress_tracker_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0)]),
        ),
    ]
