# Generated by Django 3.1 on 2020-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20200911_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='containerization_used',
            field=models.ManyToManyField(null=True, to='base.Containerization'),
        ),
    ]
