# Generated by Django 3.1 on 2020-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20200911_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='containerization_used',
            field=models.ManyToManyField(blank=True, to='base.Containerization'),
        ),
    ]
