# Generated by Django 3.1 on 2020-09-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20200912_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Doom',
        ),
    ]
