# Generated by Django 3.1 on 2020-09-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20200912_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doom',
        ),
    ]
