# Generated by Django 3.1 on 2020-09-12 15:51

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20200912_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', editable='false', max_length=200)),
                ('name', models.CharField(max_length=100, null=True)),
                ('aboutme', mdeditor.fields.MDTextField(null=True)),
                ('igname', models.CharField(blank=True, max_length=100, null=True)),
                ('githubid', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
