# Generated by Django 3.1 on 2020-09-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20200916_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='comment_type',
            field=models.CharField(choices=[('Suggestion', 'Suggestion'), ('Task', 'Task'), ('Update', 'Update')], default='Suggestion', max_length=20, null=True),
        ),
    ]
