# Generated by Django 3.1 on 2020-09-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20200916_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
    ]
