# Generated by Django 3.1 on 2020-09-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_aboutme_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='igname',
        ),
    ]
