# Generated by Django 3.1 on 2020-09-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Working', 'Working'), ('Discarded', 'Discarded'), ('Completed', 'Completed')], default='Queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Working', 'Working'), ('Completed', 'Completed')], default='Working', max_length=20),
        ),
    ]
