# Generated by Django 3.1 on 2020-09-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='choice3',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], editable='false', max_length=4),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
