# Generated by Django 3.1 on 2020-09-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200903_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='choice2',
            field=models.CharField(choices=[('New feature suggestion', 'New feature suggestion'), ('General comments', 'General comments'), ('Bug / Something does not work as expected', 'Bug / Something does not work as expected'), ('Other (please specify)', 'Other (please specify)')], editable='false', max_length=100),
        ),
    ]
