# Generated by Django 3.1 on 2020-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200904_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='choice1',
            field=models.CharField(choices=[('Extremely useful', 'Extremely useful'), ('Somewhat useful', 'Somewhat useful'), ('Not useful', 'Not useful')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='choice2',
            field=models.CharField(choices=[('New feature suggestion', 'New feature suggestion'), ('General comments', 'General comments'), ('Bug / Something does not work as expected', 'Bug / Something does not work as expected'), ('Other (please specify)', 'Other (please specify)')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='choice3',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
