# Generated by Django 3.1 on 2020-09-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20200910_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='tracker_title',
        ),
    ]
