# Generated by Django 3.1 on 2020-09-10 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20200910_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
