# Generated by Django 3.1 on 2020-09-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_delete_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='components_used',
            field=models.ManyToManyField(to='base.Components'),
        ),
    ]
