# Generated by Django 3.1 on 2020-09-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('base', '0033_auto_20200911_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Components',
            new_name='Containerization',
        ),
        migrations.RenameField(
            model_name='containerization',
            old_name='component_name',
            new_name='container_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='components_used',
        ),
        migrations.AddField(
            model_name='project',
            name='containerization_used',
            field=models.ManyToManyField(to='base.Containerization'),
        ),
        migrations.AddField(
            model_name='project',
            name='database_used',
            field=models.ManyToManyField(to='base.Database'),
        ),
        migrations.AddField(
            model_name='project',
            name='framework_used',
            field=models.ManyToManyField(to='base.Framework'),
        ),
        migrations.AddField(
            model_name='project',
            name='language_used',
            field=models.ManyToManyField(to='base.Language'),
        ),
    ]
