# Generated by Django 3.1 on 2020-09-12 14:19

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20200912_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('about_me', mdeditor.fields.MDTextField()),
                ('igname', models.CharField(blank=True, max_length=200, null=True)),
                ('githubid', models.CharField(max_length=100)),
            ],
        ),
    ]
