# Generated by Django 3.1 on 2020-09-12 15:46

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='suggestion',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='aboutme',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
