# Generated by Django 3.1 on 2020-09-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_progress_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='tracker_description',
            field=models.TextField(max_length=200),
        ),
    ]
