# Generated by Django 3.1 on 2020-09-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_blog_blog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_created']},
        ),
    ]
