# Generated by Django 3.1 on 2020-09-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20200925_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='igname',
        ),
    ]
