# Generated by Django 3.1 on 2020-09-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20200926_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_name',
            field=models.CharField(max_length=50),
        ),
    ]
