# Generated by Django 3.1 on 2020-09-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_auto_20200926_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={},
        ),
    ]
