# Generated by Django 3.1 on 2020-09-28 06:49

from django.db import migrations, models
import hashid_field.field
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20200928_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugTracker',
            fields=[
                ('tracking_id', hashid_field.field.HashidAutoField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', min_length=8, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bug', models.CharField(max_length=200)),
                ('bug_severity', models.CharField(choices=[('Low', 'Low'), ('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], default=None, max_length=10)),
                ('bug_description', mdeditor.fields.MDTextField()),
                ('user_device_info', models.TextField()),
            ],
        ),
    ]
