# Generated by Django 3.1 on 2020-09-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_auto_20200928_0706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BugTracker',
            new_name='Bug',
        ),
    ]
