# Generated by Django 3.1 on 2020-09-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20200928_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='user_device_information',
        ),
    ]
