# Generated by Django 3.1 on 2020-09-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_remove_bug_user_device_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='user_device_information',
            field=models.TextField(blank=True),
        ),
    ]
