# Generated by Django 3.1 on 2020-09-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_bug_user_device_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bug',
            new_name='Bugs',
        ),
    ]
