# Generated by Django 3.1 on 2020-09-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20200928_0749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bugs',
            new_name='Bug',
        ),
    ]
