# Generated by Django 3.1 on 2020-09-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_auto_20200928_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='ticket_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Open', max_length=10),
        ),
    ]
