# Generated by Django 3.1 on 2020-09-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_bugcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugcomments',
            old_name='email',
            new_name='user',
        ),
    ]
