# Generated by Django 3.1 on 2020-09-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20200929_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugcomments',
            old_name='email',
            new_name='user',
        ),
    ]
