# Generated by Django 3.1 on 2020-09-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20200929_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hosted',
            field=models.BooleanField(default=False),
        ),
    ]
