# Generated by Django 3.1 on 2020-09-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_project_hosted'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='converted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
