# Generated by Django 3.1 on 2020-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_progress_converted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='converted',
            field=models.BooleanField(blank=True),
        ),
    ]
