# Generated by Django 3.1 on 2020-09-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20200929_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='converted',
        ),
    ]
