# Generated by Django 3.1 on 2020-10-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_progress_converted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='dockerhub_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
