# Generated by Django 3.1 on 2020-10-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_20201003_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='dockerhubid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
