# Generated by Django 3.1 on 2020-10-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_aboutme_dockerhubid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_bug',
            field=models.BooleanField(default=False),
        ),
    ]
