name: Docker Image CI (build and push to dockerhub)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: docker login
      uses: docker/login-action@v1
      with: 
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKET_PASSWORD }}
    - 
      name: Build the Docker image
      uses: actions/checkout@v2             
        run:|
        docker build . --file Dockerfile --tag ragade:$(date +%s)
